PACKAGE_NAME="sp5100-tco-legacy"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="sp5100_tco"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_NAME[0]="sp5100_tco"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
